import { CONFIG, GameStatus } from "./config.js";

/* ---------- The central Game State Object ---------- */
export const GameState = {
  status:   GameStatus.BOOT,
  cityName: "Demos",
  year:     CONFIG.START_YEAR,   // counts DOWN (BC)
  turn:     0,
  phase:    CONFIG.PHASE_NAME,

  // Early-game survival resources.
  stats: {
    population: 120,   // total headcount
    grain:      72,    // primary food source (a lean buffer — survival is precarious)
    cattle:     8,     // animal wealth — early-game currency
    olives:     0,     // long-term investment / hygiene asset — earned by labour
    grapes:     0,     // social catalyst / ritual drink — earned by labour
    timber:     0,     // structural material — earned by labour
    clay:       0,     // structural material — earned by labour
    stone:      0,     // masonry — only once the Mines are dug; essential to later building
  },

  // Macro-variables: the cultural & religious standing of the Polis.
  macros: {
    kleos:    0,   // Renown / Glory — draws wandering migrants
    eusebeia: 0,   // Piety — a buffer spent to weather crises
  },

  // Accumulated citizen discontent (eased by the Hekatomb feast).
  unhappiness: 0,

  // An unresolved Hekatomb festival awaiting the player's offerings.
  pendingFestival: false,
  festivalAlloc: { cattle: 0, grapes: 0, grain: 0 },

  // Player-set labour allocation (relative weights per trade).
  jobAllocation: {},

  // Current turn's job head-counts (derived from the allocation; for display).
  jobs: {},

  // Synoikismos: runtime copy of the neighbouring hamlets.
  hamlets: [],

  // Permanent per-turn resource bonuses gained from absorbed hamlets.
  bonuses: {},

  // Citizens permanently withdrawn into full-time priesthood (Olympian temene).
  priests: 0,

  // Religion: the Ancestral Hearth opens the Divine Epiphany; gods are named
  // as Daimones and ascend through survived Mythic Cycles.
  hearthBuilt: false,
  hearthTurn:  -1,                // turn the Hearth was kindled (schedules Epiphanies)
  pendingEpiphany: false,         // a fresh card-grant notice awaits acknowledgement
  hand: { aspects: [], epithets: [] },  // unassigned Aspect/Epithet cards in the people's keeping
  relSelect: { aspect: null, epithet: null },  // cards selected at the founding bench (preview before committing)
  gods: [],                       // consecrated gods (Daimones → Heroes → Olympians)
  godSeq: 0,                      // id sequence for gods
  winter: 0,                      // turns of the current Great Winter remaining (0 = not winter)
  pendingMyth: null,              // an unresolved Mythic Cycle story (blocks the turn)
  pendingChoice: null,            // an unresolved respond-able flavour/catastrophe event (blocks the turn)

  // Knowledge: the independent research economy (Ergon + Muthos) and its tree.
  ergon:  0,                      // ⚒ practical know-how, generated by labour
  muthos: 0,                      // 📜 lore & story, generated by cultural life
  techs:  {},                     // researched technologies (id -> true)
  research: { halted: false, reason: "" },  // last tick's research state (for the panel)
  fieldRevealed: false,           // terraced field shown on the map (Terraced Farming)
  techBonus: { grain: 0, grapes: 0, clay: 0, timber: 0, stone: 0 },  // per-turn production added by tech/buildings
  buildings: { mines: false, docks: false },   // built structures
  minesTurn: -1, docksTurn: -1,                // turns they were raised
  alphabetUnlocked: false,                     // the Phoenician negotiation has been won
  pendingPhoenician: null,                     // an unresolved Phoenician minigame (blocks the turn)
  merchantSeq: 0,                              // count of foreign-merchant visits
  phoenicianFailTurn: -99,                     // turn the last Phoenician courtship was spurned
  ergonMult: 1, muthosMult: 1,    // generation multipliers raised by tech

  // An unresolved crisis awaiting the player's response, if any.
  pendingCrisis: null,

  // Turns of civil unrest remaining (from a failed annexation).
  unrest: 0,

  // Net deltas captured during the last tick, used for "+5"/"-2" text.
  lastDeltas: {},

  // The chronicle: an append-only list of historical entries.
  chronicle: [],

  // Social Orders: three ranks whose Clout (political weight, summing to 100%)
  // and Satisfaction (0–100) together set the Polis's Discontent. Driven each
  // year by the labour sliders and tech unlocks (see js/social.js).
  socialClasses: {
    oikosLords: { clout: 50, satisfaction: 80 },
    autourgoi:  { clout: 35, satisfaction: 75 },
    akleroi:    { clout: 15, satisfaction: 70 },
  },
  globalDiscontent: 0,           // derived top-bar discontent (0 = content, 100 = seething)
  lastGrainBalance: 0,           // last tick's grain surplus (for mood read-outs)
  archaicEra: false,             // set when the Phoenician Alphabet closes the Dawn Era

  // Threat-forecast clock: dangers scheduled ahead of time as visible omens.
  // Each: { type:"crisis"|"catastrophe", id, name, icon, domain, due } (see js/threats.js).
  threats: [],

  // Work-site capacity earned beyond each trade's base (from tech, buildings and
  // absorbed hamlets); added to JOBS[key].capacity. Keyed by job.
  capacityBonus: {},
};
